import {Poppins} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";

const inter = Poppins({subsets: ["latin"], weight: ["500", "400", '600', '700'], style: ['normal']});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}><AntdRegistry>{children}</AntdRegistry></body>
        </html>
    );
}
